MVC Task/UserMVC/UserMVC/Models/ErrorViewModel.cs
using System;

namespace UserMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC Task/UserMVC/UserMVC/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using User.Core.ConnectingApi;
using User.Core.Model;
using User.Core.CoreController;

namespace UserMVC.Controllers
{
    public class CustomerController : Controller
    {
        public IActionResult CustomerSearch()
        {
            return View();
        }

        public IActionResult MainCustomer()
        {
            return View();
        }

        public IActionResult AddCustomer()
        {
            return View();
        }

        [HttpPost]
        public ViewResult CustomerSearch(SearchCustomer customer)
        {
            SearchCustomer customerResult = new SearchCustomer();
            customerResult = CoreCustomerController.Search(customer);

            if (customerResult.responses.Count != 0)
                return View(customerResult);
            else
            {
                ViewBag.NoneCustomer = "Customer not found";
                return View();
            }
        }

        [HttpPost]
        public ViewResult GetAllInfo(SearchCustomer customer)
        {
            customer.Id = 1;
            SearchCustomer customerResult = new SearchCustomer();
            customerResult = CoreCustomerController.GetCutomerById(customer);

            return View("MainCustomer", customerResult);
        }

        [HttpPost]
        public ViewResult SaveCustomer(SearchCustomer customer)
        {

            if (ModelState.IsValid)
            {
                var x = CoreCustomerController.SaveCustomer(customer);

                if ((int)x.Result == 1)
                {
                    return GetAllInfo(customer);
                }
                else
                {
                    ViewBag.ErrorMessage = x.Description;
                    return View("Login");
                }
            }
            else
            {
                return View("AddCustomer");
            }
        }

    }
}

MVC Task/UserMVC/UserMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using User.Core.CoreController;
using User.Core.Helper;
using User.Core.Model;
using UserMVC.Models;

namespace UserMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Login()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult LoginUser(Users login)
        {
            if (ModelState.IsValid)
            {
                login.UserPassword = MD5.CreateMD5(login.UserPassword);
                var x = UserController.LoginUserAsync(login);

                if ((int)x.Result == 1)
                {
                    return View("~/Views/Customer/CustomerSearch.cshtml");
                }
                else
                {
                    ViewBag.ErrorMessage = x.Description;
                    return View("Login");
                }
            }
            else
            {
                return View("Login");
            }
        }
    }
}

MVC Task/UserMVC/UserMVC/Views/Customer/AddCustomer.cshtml
@model User.Core.Model.SearchCustomer

@{
    ViewData["Title"] = "Add Customer";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/Login.css" type="text/css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body>

    <h2 style="text-align:center">Add Customer</h2>

    <div class="container">
        <form asp-action="SaveCustomer" method="post" asp-controller="Customer">

            <div asp-validation-summary="All"></div>
            <div class="row">
                <div class="col-25">
                    <label for="fname">LastName</label>
                </div>
                <div class="col-75">
                    <input type="text" placeholder="LastName.." asp-for="@Model.CustomerName">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">FirstName</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="text" placeholder="FirstName.." asp-for="@Model.CustomerSurname">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">Father Name</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="text" placeholder="FatherName.." asp-for="@Model.FathersName">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">Email</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="text" placeholder="Email.." asp-for="@Model.Email">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">Date Of Birth</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="date" placeholder="DateOfBirth.." asp-for="@Model.DateOfBirth">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">Gender</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <select asp-for="@Model.Gender">
                        <option>Male</option>
                        <option>Female</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">Address</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="text" placeholder="customerAddress.." asp-for="@Model.CustomerAddress">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">City</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="text" placeholder="city.." asp-for="@Model.City">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">Region</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="text" placeholder="Region.." asp-for="@Model.Region">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">Phone</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="text" placeholder="phone.." asp-for="@Model.Phone">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">Postal Code</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="text" placeholder="Postal code.." asp-for="@Model.PostalCode">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">Fax</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="text" placeholder="Fax.." asp-for="@Model.Fax">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">Pasport</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="text" placeholder="Pasport.." asp-for="@Model.PersonDocument">
                </div>
            </div>

            <button class="button vertical-center">Button</button>
        </form>

        <h1>aa</h1>

    </div>

</body>
</html>

MVC Task/UserMVC/UserMVC/Views/Customer/CustomerSearch.cshtml
@model User.Core.Model.SearchCustomer

@{
    ViewData["Title"] = "Search Customer";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/Login.css" type="text/css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        #customers {
            overflow: scroll;
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

            #customers td, #customers th {
                border: 1px solid #ddd;
                padding: 8px;
            }

            #customers tr:nth-child(even) {
                background-color: #f2f2f2;
            }

            #customers tr:hover {
                background-color: #ddd;
            }

            #customers th {
                padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: #4CAF50;
                color: white;
            }
    </style>

</head>
<body>

    <h2 style="text-align:center">Wellcome</h2>

    <div class="container">
        <form asp-action="CustomerSearch" method="post" asp-controller="Customer">

            <h1 style="color: red; align-content: center">@ViewBag.NoneCustomer</h1>

            <div class="row">
                <div class="col-25">
                    <label for="fname">LastName</label>
                </div>
                <div class="col-75">
                    <input type="text" placeholder="LastName.." asp-for="@Model.CustomerName">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">FirstName</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="text" placeholder="FirstName.." asp-for="@Model.CustomerSurname">
                </div>
            </div>

            <div class="row">
                <div class="col-25">
                    <label for="lname">Pasport</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="text" placeholder="Pasport.." asp-for="@Model.PersonDocument">
                </div>
            </div>

            <div class="row">
                <div class="col-25">
                    <label for="lname">Email</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="text" placeholder="Email.." asp-for="@Model.Email">
                </div>
            </div>


            <button class="button vertical-center">Button</button>
        </form>

        <div style="overflow: scroll; height: 550px;">
            @if (Model != null)
            {
                @foreach (var item in Model.Customers)
                {

                    <table id="customers">
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Lastname</th>
                            <th>Father name</th>
                            <th>Email</th>
                            <th>Pasport</th>
                            <th>AllProp</th>
                        </tr>
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.CustomerName</td>
                            <td>@item.CustomerSurname</td>
                            <td>@item.FathersName</td>
                            <td>@item.Email</td>
                            <td>@item.PersonDocument</td>
                            <td><form asp-controller="Customer" asp-action="GetAllInfo" method="post"><button>All</button></form></td>
                        </tr>
                    </table>
                }
            }
        </div>


    </div>

</body>
</html>

MVC Task/UserMVC/UserMVC/Views/Customer/MainCustomer.cshtml
@model User.Core.Model.SearchCustomer

@{
    ViewData["Title"] = "Main Customer";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/Login.css" type="text/css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
    </style>

</head>
<body>

    <h2 style="text-align:center">Wellcome @Model.CustomerName @Model.CustomerSurname</h2>

    <div class="container">


    </div>

</body>
</html>

MVC Task/UserMVC/UserMVC/Views/Home/Login.cshtml
@model User.Core.Model.Users;

@{
    Layout = null;
    ViewData["Title"] = "Login User";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/Login.css" type="text/css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <h2 style="text-align:center">Wellcome</h2>

    <div class="container">
        <form asp-action="LoginUser" asp-controller="Home" method="post">
            <h1 style="color: red; text-align:center">@ViewBag.ErrorMessage</h1>
            <div class="row">
                <div class="col-25">
                    <label for="fname">UserName</label>
                </div>
                <div class="col-75">
                    <input type="text" placeholder="User name.." asp-for="@Model.UserName">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">Password</label>
                </div>
                <div class="col-75" style="text-align:center">
                    <input type="text" placeholder="Your Password.." asp-for="@Model.UserPassword">
                </div>
            </div>

            <div asp-validation-summary="All"></div>

            <button class="button vertical-center">Button</button>
        </form>
    </div>

</body>
</html>

MVC Task/UserMVC/UserMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UserMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UserMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="CustomerSearch">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">LogOut</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="AddCustomer">Add customer</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
            @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - UserMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>